spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  application:
    name: FinalProject
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB}
    user: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    port: 587
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 86400000
      refresh-token:
        expiration: 604800000
  mail:
    expiration: 900000

server:
  port: 8080
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html